[@ww.textfield labelKey="apprendaDeploy.url" name="url" required='true'/]
[@ww.textfield labelKey="apprendaDeploy.username" name="username" required='true'/]
[@ww.textfield labelKey="apprendaDeploy.password" name="password" required='true'/]
[@ww.textfield labelKey="apprendaDeploy.tenant" name="tenant" required='true'/]
[@ww.checkbox labelKey="apprendaDeploy.remove" name="remove"/]
[@ww.textfield labelKey="apprendaDeploy.appAlias" name="appAlias" required='true'/]
[@ww.textfield labelKey="apprendaDeploy.verAlias" name="verAlias" required='true'/]
[@ww.textfield labelKey="apprendaDeploy.archiveName" name="archiveName" required='true'/]
[@ww.select labelKey="apprendaDeploy.stage" name="stage" list="stageList" listKey='Id' listValue='Value' required='true'/]